In [1]:
# Section B: Numpy
# 1.	Create:
# - A scalar using np.array(5)
# - A 1D array with values 1 to 5
# - A 2D array (2x3) with values from 10 to 60 in steps of 10

In [2]:
import numpy as np

In [3]:
# Scalar

In [4]:
scalar = np.array(5)
print("scalar :",scalar)

scalar : 5


In [5]:
# 1D array

In [6]:
arr_id = np.array([1,2,3,4,5])
print("1d array :", arr_id)

1d array : [1 2 3 4 5]


In [7]:
# 2D Array (2 * 3)

In [8]:
arr_2d = np.array([[10,20,30],[40,50,60]])
print("2d array:",arr_2d)

2d array: [[10 20 30]
 [40 50 60]]


In [9]:
# 2.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [10]:
random_arr = np.random.randint(0, 100 ,(4, 4))
print(random_arr)

[[13 34 24 56]
 [82 16 22 12]
 [52 84 39 97]
 [53 60  4 22]]


In [11]:

# 3.	Create a 2D numpy array of shape (3x3). Convert it into a pandas
#       DataFrame and add column names: 'A', 'B', 'C'.

In [12]:
import pandas as pd

In [13]:
array_3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
df_np = pd.DataFrame(array_3 , columns = ["a","b","c"])
print(df_np)

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9


In [15]:

# Section C: Exploring Pandas
# 1.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
# - Use .info(), .describe()
# - Select 'Name' and 'City' columns
# - Drop 'City' column
# - Fill any missing values in 'Salary' column with the mean
# - Remove any duplicate rows

In [16]:
# Create DataFrame

In [17]:
data = {
        "name"   : ["a","b","c","d","e","f","g","h"] ,
        "age"    : [22,23,24,22,25,26,23,21] ,
        "city"   : ["Pume" ,"mumbai","nashik","pune","banglore","mumbai","pune","nashik"] ,
        "salary" : [50000,48000,None,60000,50000,70000,None,60000]
        }

In [18]:
df = pd.DataFrame(data)

In [19]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    8 non-null      object 
 1   age     8 non-null      int64  
 2   city    8 non-null      object 
 3   salary  6 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 388.0+ bytes


age        salary
count   8.000000      6.000000
mean   23.250000  56333.333333
std     1.669046   8524.474568
min    21.000000  48000.000000
25%    22.000000  50000.000000
50%    23.000000  55000.000000
75%    24.250000  60000.000000
max    26.000000  70000.000000

In [20]:
# Select 'Name' and 'City' columns

In [21]:
df[["name" , "city"]]

name      city
0    a      Pume
1    b    mumbai
2    c    nashik
3    d      pune
4    e  banglore
5    f    mumbai
6    g      pune
7    h    nashik

In [22]:
# - Drop 'City' column

In [23]:
df = df.drop("city",axis = 1)
df

name  age   salary
0    a   22  50000.0
1    b   23  48000.0
2    c   24      NaN
3    d   22  60000.0
4    e   25  50000.0
5    f   26  70000.0
6    g   23      NaN
7    h   21  60000.0

In [24]:
# - Fill any missing values in 'Salary' column with the mean

In [25]:
df["salary"] = df["salary"].fillna(df["salary"].mean())
df

name  age        salary
0    a   22  50000.000000
1    b   23  48000.000000
2    c   24  56333.333333
3    d   22  60000.000000
4    e   25  50000.000000
5    f   26  70000.000000
6    g   23  56333.333333
7    h   21  60000.000000

In [26]:
#  - Remove any duplicate rows

In [27]:
df = df.drop_duplicates()
